CREATE TABLE PLANO(
	ID		UNIQUEIDENTIFIER		NOT NULL,
	NOME	NVARCHAR(50)			NOT NULL UNIQUE,
	PRIMARY KEY(ID))
GO

CREATE TABLE CLIENTE(
	ID		UNIQUEIDENTIFIER		NOT NULL,
	NOME	NVARCHAR(150)			NOT	NULL,
	CPF		NVARCHAR(11)			NOT	NULL UNIQUE,
	IDPLANO UNIQUEIDENTIFIER		NOT	NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDPLANO) REFERENCES PLANO(ID))
GO

CREATE PROCEDURE SP_INSERIR_PLANO
	@NOME	NVARCHAR(50)
AS
BEGIN
	BEGIN TRANSACTION
	INSERT INTO PLANO(ID, NOME) VALUES(NEWID(), @NOME)
	COMMIT
END	 
GO

CREATE PROCEDURE SP_ALTERAR_PLANO
	@ID			UNIQUEIDENTIFIER,
	@NOME		NVARCHAR(50)
AS
BEGIN
	BEGIN TRANSACTION
	UPDATE PLANO SET NOME = @NOME WHERE ID = @ID
	COMMIT
END
GO

CREATE PROCEDURE SP_EXCLUIR_PLANO
	@ID				UNIQUEIDENTIFIER
AS
BEGIN
	BEGIN TRANSACTION
	DELETE PLANO WHERE ID = @ID
	COMMIT
END
GO

CREATE PROCEDURE SP_INSERIR_CLIENTE
	@NOME		NVARCHAR(150),
	@CPF		NVARCHAR(11),
	@IDPLANO	UNIQUEIDENTIFIER
AS
BEGIN
	BEGIN TRANSACTION
	INSERT INTO CLIENTE(ID, NOME, CPF, IDPLANO) VALUES(NEWID(), @NOME, @CPF, @IDPLANO)
	COMMIT
END
GO


CREATE PROCEDURE SP_ALTERAR_CLIENTE
	@ID				UNIQUEIDENTIFIER,
	@NOME			NVARCHAR(150),
	@CPF			NVARCHAR(11),
	@IDPLANO		UNIQUEIDENTIFIER
AS
BEGIN
	BEGIN TRANSACTION
	UPDATE CLIENTE SET NOME = @NOME, CPF = @CPF, IDPLANO = @IDPLANO WHERE ID = @ID
	COMMIT
END
GO

CREATE PROCEDURE SP_EXCLUIR_CLIENTE
	@ID				UNIQUEIDENTIFIER
AS
BEGIN
	BEGIN TRANSACTION
	DELETE CLIENTE WHERE ID = @ID
	COMMIT
END
GO